name: amorphouspy-meltquench
channels:
  - conda-forge
dependencies:
  - python=3.13
  - lammps=2024.08.29=*mpi_openmpi*
  - ase
  - lammpsparser
  - numba
  - numpy
  - pandas
  - scipy
  - networkx
  - pymatgen
  - matplotlib
  - jupyter
  - pip
  - pip:
    - amorphouspy
    - PyMCubes
