channels:
  - conda-forge
dependencies:
  - python=3.13.*
  - lammps==2024.08.29
  - ase
  - numpy
  - pandas
  - pymatgen
  - scipy
  - networkx
  - numba
  - lammpsparser
  - matplotlib
  - ipykernel
  - jupyter
  - papermill
  - pip:
      - amorphouspy>=0.5.7
